USE [FB2DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_S_ASSESS_UPD_SIGN_LOG]    Script Date: 2026/7/29 下午 03:26:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_S_FASSESS_UPD_SIGN_LOG] 
	@ASSESS_YEAR VARCHAR(4),
	@ASSESS_TYPE VARCHAR(1),
	@HEAD_EMP_ID VARCHAR(5) ,
	@USERID varchar(20),
	@FUNCID varchar(30)
AS 
BEGIN

	DECLARE @pErr INT = 0;
	DECLARE @pErrMsg VARCHAR(1000) = NULL;
	DECLARE @proc_id_previous VARCHAR(60) = '';
	DECLARE @proc_id VARCHAR(60) = 'SP_S_FASSESS_UPD_SIGN_LOG';
	DECLARE @proc_desc NVARCHAR(120) = '整批新增主管簽核記錄';
	DECLARE @proc_scheduling VARCHAR(30) = 'CALL';
	DECLARE @proc_log NVARCHAR(600) = NULL;
	DECLARE @proc_status VARCHAR(1) = NULL;

	

   BEGIN TRANSACTION TB_S_M_FOREIGN_ALL_LOG
   BEGIN TRY
	IF @FUNCID='FB2SJ370'
		BEGIN
		INSERT INTO TB_S_M_FOREIGN_ALL_LOG(ASSESS_YEAR, ASSESS_TYPE, EMP_ID, SEQ_NO, GRADE, MEMO, LEVEL_RATE,
		                                  CREATED_BY, CREATED_DT, FUNC_ID)		
		SELECT 
             A.ASSESS_YEAR, A.ASSESS_TYPE, A.EMP_ID, 
			 ISNULL((SELECT MAX(SEQ_NO)+1 FROM TB_S_M_FOREIGN_ALL_LOG WHERE ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID),0)+1 AS SEQ_NO,
	         CASE WHEN ISNULL((SELECT TOP 1 GRADE FROM TB_S_M_FOREIGN_LOG WHERE ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID AND CREATED_BY=@HEAD_EMP_ID  AND FUNC_ID=@FUNCID order by CREATED_DT DESC),'')<>'' THEN
			 (SELECT TOP 1 GRADE FROM TB_S_M_FOREIGN_LOG WHERE ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID AND CREATED_BY=@HEAD_EMP_ID  AND FUNC_ID=@FUNCID order by CREATED_DT DESC) ELSE  A.SCORE_FINAL END AS GRADE,
			  CASE WHEN ISNULL((SELECT TOP 1 MEMO FROM TB_S_M_FOREIGN_LOG WHERE ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID AND CREATED_BY=@HEAD_EMP_ID AND FUNC_ID=@FUNCID order by CREATED_DT DESC),'')<>'' THEN
			 (SELECT TOP 1 MEMO FROM TB_S_M_FOREIGN_LOG WHERE ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID AND CREATED_BY=@HEAD_EMP_ID  AND FUNC_ID=@FUNCID order by CREATED_DT DESC) ELSE  '' END AS MEMO,
			  (select LEVEL_RATE  from TB_S_M_FOREIGN_DEPT_LEVEL  where  DEPT_LEVEL>='20' AND ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE AND HEAD_EMP_ID=@HEAD_EMP_ID AND ASSESS_YEAR=A.ASSESS_YEAR AND ASSESS_TYPE=A.ASSESS_TYPE)LEVEL_RATE,
			@USERID,GETDATE(),@FUNCID
        FROM TB_S_M_FOREIGN_DIRECTOR_D E left join
                TB_S_M_FOREIGN_TARGET A  on E.ASSESS_YEAR=A.ASSESS_YEAR and E.ASSESS_TYPE=A.ASSESS_TYPE and E.EMP_ID=A.EMP_ID left join
                TB_S_M_FOREIGN_DIRECTOR_H D on E.ASSESS_YEAR=E.ASSESS_YEAR and E.ASSESS_TYPE=D.ASSESS_TYPE and E.DEPT_NO=D.DEPT_NO  AND E.DIREC_EMP_ID=D.DIREC_EMP_ID
        where E.ASSESS_YEAR=@ASSESS_YEAR and E.ASSESS_TYPE= @ASSESS_TYPE  and A.EMP_ID<>@HEAD_EMP_ID and
                D.LEVEL_RATE in(
	            SELECT Y.LEVEL_RATE
		        FROM
						(select LEVEL_RATE ,ASSESS_YEAR ,ASSESS_TYPE, DEPT_NO, HEAD_EMP_ID from TB_S_M_FOREIGN_DEPT_LEVEL  where  DEPT_LEVEL>='20') X left join 
					TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR and X.ASSESS_TYPE=Y.ASSESS_TYPE
					where X.ASSESS_YEAR=E.ASSESS_YEAR and X.ASSESS_TYPE=E.ASSESS_TYPE and X.HEAD_EMP_ID=@HEAD_EMP_ID 
	            ) 
		END;
	
	
		COMMIT TRANSACTION TB_S_M_FOREIGN_ALL_LOG;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION TB_S_M_FOREIGN_ALL_LOG;
		SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[TB_H_R_SP_LOG:INSERT]'+ERROR_MESSAGE();
		GOTO WriteLog;
	END CATCH

	WriteLog:
	--新增SP記錄檔
	IF @pErr = 0 BEGIN
		SET @proc_status = 'Y';
		SET @proc_log = '處理成功';
	END
	ELSE BEGIN
		IF @proc_status IS NULL SET @proc_status = 'E';
		SET @proc_log = left(@pErrMsg, 600);
	END
	
	BEGIN TRANSACTION ADD_TB_H_R_SP_LOG
		BEGIN TRY
			INSERT INTO TB_H_R_SP_LOG(PROC_ID, PROC_BASE_DT, PROC_DESC, PROC_OTH_DESC, PROC_DT, PROC_STATUS, PROC_LOG, UPDATED_BY, FUNC_ID)
			VALUES(@proc_id, GETDATE(), @proc_desc, NULL, CURRENT_TIMESTAMP, @proc_status, @proc_log, @USERID, @FUNCID);
		COMMIT TRANSACTION ADD_TB_H_R_SP_LOG;
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION ADD_TB_H_R_SP_LOG;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[ADD_TB_H_R_SP_LOG:INSERT]:' + ERROR_MESSAGE();
		END CATCH
	

	RETURN (@pErr)
END;






GO


