USE [FB2DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_S_FASSESS_GEN_L2_DATA]    Script Date: 2026/7/29 下午 03:50:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_S_FASSESS_GEN_L2_DATA] @ASSESS_YEAR VARCHAR(4)
	,@ASSESS_TYPE VARCHAR(1) 
	,@USERID varchar(20)
	,@FUNCID varchar(30)
AS 
BEGIN
SET NOCOUNT ON;
	--錯誤訊息
	DECLARE @pRowCount INT =0;
	DECLARE @pErr INT = 0;
	DECLARE @pErrMsg VARCHAR(1000) = NULL;
	
	DECLARE @proc_id_previous VARCHAR(60) = 'SP_S_FASSESS_GEN_L2_DATA';
	DECLARE @proc_id VARCHAR(60) = 'SP_S_FASSESS_GEN_L2_DATA';
	DECLARE @proc_desc NVARCHAR(120) = '第二階段考課生成';
	DECLARE @proc_scheduling VARCHAR(30) = 'CALL';
	DECLARE @proc_log NVARCHAR(600) = NULL;
	DECLARE @proc_status VARCHAR(1) = NULL;
	DECLARE @proc_y_cnt INT;
	DECLARE @ori_dept_no  VARCHAR(7) = '';
	DECLARE @chg_dept_no  VARCHAR(7) = '';

BEGIN
TRY
--刪除
--DELETE FROM TB_S_M_ASSESS_ITEM_YEAR where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE;
--insert into TB_S_M_ASSESS_ITEM_YEAR(ASSESS_YEAR,ASSESS_TYPE,WS_CD,LEVEL_CD,PJOB_TYPE,ITEM_GROUP,
--                                    CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,FUNC_ID)
--select @ASSESS_YEAR,@ASSESS_TYPE,WS_CD,LEVEL_CD,PJOB_TYPE,ITEM_GROUP,
--       @USERID,GETDATE(),@USERID,GETDATE(),@FUNCID
--from   TB_S_M_ASSESS_ITEM
--WHERE  ASSESS_TYPE=@ASSESS_TYPE;

--處理TB_S_M_ASSESS_GRADEPOINT
	DELETE FROM TB_S_M_FOREIGN_GRADEPOINT where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE;
	insert into TB_S_M_FOREIGN_GRADEPOINT(ASSESS_YEAR,ASSESS_TYPE,RATING,POINT,
                                         CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,FUNC_ID)
	select @ASSESS_YEAR,@ASSESS_TYPE,RATING,POINT,
		   @USERID,GETDATE(),@USERID,GETDATE(),@FUNCID
	from   TB_S_M_FOREIGN_GRADEPOINT
	WHERE ASSESS_YEAR=@ASSESS_YEAR-1 and ASSESS_TYPE=@ASSESS_TYPE;

--處理TB_S_M_ASSESS_POINT_YEAR
	DELETE FROM TB_S_M_FOREIGN_POINT_YEAR where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE;

	insert into TB_S_M_FOREIGN_POINT_YEAR(ASSESS_YEAR,ASSESS_TYPE,WS_CD,LEVEL_CD,POINT_GROUP,point_group_name,
                                         CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,FUNC_ID)
	select @ASSESS_YEAR,@ASSESS_TYPE,WS_CD,LEVEL_CD,POINT_GROUP,point_group_name,
		   @USERID,GETDATE(),@USERID,GETDATE(),@FUNCID
	from   TB_S_M_FOREIGN_POINT
	WHERE  ASSESS_TYPE=@ASSESS_TYPE;


--產出TB_S_M_ASSESS_DEPT_LEVEL
EXECUTE dbo.SP_S_FASSESS_DEPT_LEVEL @ASSESS_YEAR,@ASSESS_TYPE,'','','','N',@USERID,@FUNCID;
print '產出TB_S_M_FOREIGN_DEPT_LEVEL結束時間:'+CONVERT(VARCHAR(30),GETDATE(),121);

--生成SP_S_ASSESS_GEN_DISTING_EMP
EXECUTE dbo.SP_S_FASSESS_GEN_DISTING_EMP @ASSESS_YEAR,@ASSESS_TYPE,'',@USERID,@FUNCID;
print '生成SP_S_FASSESS_GEN_DISTING_EMP結束時間:'+CONVERT(VARCHAR(30),GETDATE(),121);

--產出TB_S_M_ASSESS_DEP20_PEO
EXECUTE dbo.SP_S_FASSESS_GEN_DEP20_PEO @ASSESS_YEAR,@ASSESS_TYPE,'',@USERID,@FUNCID;
print '產出TB_S_M_FOREIGN_DEP20_PEO結束時間:'+CONVERT(VARCHAR(30),GETDATE(),121);

--生成TB_S_M_ASSESS_SCORE
EXECUTE dbo.SP_S_FASSESS_GEN_SCORE @ASSESS_YEAR,@ASSESS_TYPE,'',@USERID,@FUNCID;
print '生成TB_S_M_FASSESS_SCORE結束時間:'+CONVERT(VARCHAR(30),GETDATE(),121);

--print '生成SP_S_ASSESS_GEN_DISTING_EMP'
--生成SP_S_ASSESS_GEN_DIRECTOR
EXECUTE dbo.SP_S_FASSESS_GEN_DIRECTOR  @ASSESS_YEAR,@ASSESS_TYPE,'',@USERID,@FUNCID;
print '開始時間:'+CONVERT(VARCHAR(30),GETDATE(),121);
--print '生成SP_S_ASSESS_GEN_DIRECTOR'
--生成TB_S_M_ASSESS_DEP20_UP_SIGN
DELETE FROM TB_S_M_FOREIGN_DEP20_UP_SIGN where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE

INSERT INTO TB_S_M_FOREIGN_DEP20_UP_SIGN(ASSESS_YEAR,ASSESS_TYPE,DEPT_NO,DEPT_LEVEL,EMP_ID,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,FUNC_ID)
SELECT ASSESS_YEAR,ASSESS_TYPE,DEPT_NO,DEPT_LEVEL,HEAD_EMP_ID,@USERID,getDate(),@USERID,getDate(),@FUNCID
FROM TB_S_M_FOREIGN_DEPT_LEVEL where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE and len(LEVEL_RATE)<=6

END TRY
BEGIN CATCH
	SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[TB_H_R_SP_LOG:INSERT]'+ERROR_MESSAGE();
	GOTO WriteLog;
END CATCH

WriteLog:
	--新增SP記錄檔
	IF @pErr = 0 BEGIN
		SET @proc_status = 'Y';
		SET @proc_log = '處理成功';
	END
	ELSE BEGIN
		IF @proc_status IS NULL SET @proc_status = 'E';
		SET @proc_log = left(@pErrMsg, 600);
	END
	
	BEGIN TRANSACTION ADD_TB_H_R_SP_LOG
		BEGIN TRY
			INSERT INTO TB_H_R_SP_LOG(PROC_ID, PROC_BASE_DT, PROC_DESC, PROC_OTH_DESC, PROC_DT, PROC_STATUS, PROC_LOG, UPDATED_BY, FUNC_ID)
			VALUES(@proc_id, @ASSESS_YEAR, @proc_desc, NULL, CURRENT_TIMESTAMP, @proc_status, @proc_log, @USERID, @FUNCID);
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION ADD_TB_H_R_SP_LOG;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[ADD_TB_H_R_SP_LOG:INSERT]:' + ERROR_MESSAGE();
		END CATCH
	COMMIT TRANSACTION ADD_TB_H_R_SP_LOG;

	RETURN (@pErr)
END;
 





GO


