SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_S_FASSESS_UPD_RO_DEP20_PEO] @ASSESS_YEAR VARCHAR(4),@ASSESS_TYPE VARCHAR(1),@DEPT_NO VARCHAR(7) ,
	@USERID varchar(20),
	@FUNCID varchar(30)
AS 
BEGIN

	DECLARE @pErr INT = 0;
	DECLARE @pErrMsg VARCHAR(1000) = NULL;
	DECLARE @proc_id_previous VARCHAR(60) = 'SP_S_ASSESS_DATA';
	DECLARE @proc_id VARCHAR(60) = 'SP_S_FASSESS_UPD_RO_DEP20_PEO';
	DECLARE @proc_desc NVARCHAR(120) = '更新SP_S_FASSESS_UPD_RO_DEP20_PEO';
	DECLARE @proc_scheduling VARCHAR(30) = 'CALL';
	DECLARE @proc_log NVARCHAR(600) = NULL;
	DECLARE @proc_status VARCHAR(1) = NULL;

	DECLARE @ws_cd varchar(1);
	DECLARE @score_level_group varchar(20);
	DECLARE @real_a decimal(3,0);
	DECLARE @real_b decimal(3,0);
	DECLARE @real_c decimal(3,0);
	DECLARE @real_d decimal(3,0);
	DECLARE @real_e decimal(3,0);
	DECLARE @out_a decimal(3,0);
	DECLARE @out_b decimal(3,0);
	DECLARE @out_c decimal(3,0);
	DECLARE @out_d decimal(3,0);
	DECLARE @out_e decimal(3,0);

	DECLARE cur_dept_20_peo CURSOR FOR
	Select O.WS_CD, O.SCORE_LEVEL_GROUP
		   ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='A' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RA
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='B' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RB
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='C' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RC
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='D' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RD
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='E' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RE
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='A' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OA
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='B' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OB
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='C' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OC
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='D' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OD
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD and CHARINDEX(A.LEVEL_CD,O.SCORE_LEVEL_GROUP)>0 and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='E' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OE
   from TB_S_M_FOREIGN_DEP20_PEO O
   where O.DEPT_NO_20=@DEPT_NO and O.IS_MERGER<>'A' and O.SCORE_LEVEL_GROUP<>'' AND O.ASSESS_YEAR=@ASSESS_YEAR AND O.ASSESS_TYPE=@ASSESS_TYPE
   union
   	Select O.WS_CD, O.SCORE_LEVEL_GROUP
		   ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='A' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RA
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='B' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RB
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='C' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RC
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='D' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RD
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='N' and A.SCORE_DEPT='E' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))RE
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='A' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OA
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='B' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OB
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='C' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OC
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='D' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OD
     ,(select count(*) 
	from TB_S_M_FOREIGN_TARGET A left join   
	     TB_S_M_FOREIGN_DIRECTOR_D B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID  
	where A.ASSESS_YEAR=O.ASSESS_YEAR and A.ASSESS_TYPE=O.ASSESS_TYPE and WS_CD=O.WS_CD  and isnull(A.is_OUT,'N')='Y' and A.SCORE_DEPT='E' and B.DEPT_NO in  
	 (  
 		SELECT Y.DEPT_NO  
 		FROM  
 			(select LEVEL_RATE ,ASSESS_YEAR, ASSESS_TYPE from TB_S_M_FOREIGN_DEPT_LEVEL  where DEPT_NO=@DEPT_NO and DEPT_LEVEL>='20') X left join   
 									TB_S_M_FOREIGN_DEPT_LEVEL Y on SUBSTRING(Y.LEVEL_RATE,1,len(X.LEVEL_RATE))=X.LEVEL_RATE  and X.ASSESS_YEAR=Y.ASSESS_YEAR  and  X.ASSESS_TYPE=Y.ASSESS_TYPE
 			where X.ASSESS_YEAR=A.ASSESS_YEAR  AND X.ASSESS_TYPE=A.ASSESS_TYPE))OE
   from TB_S_M_FOREIGN_DEP20_PEO O
   where O.DEPT_NO_20=@DEPT_NO and O.IS_MERGER<>'A' and O.SCORE_LEVEL_GROUP=''  AND O.ASSESS_YEAR=@ASSESS_YEAR AND O.ASSESS_TYPE=@ASSESS_TYPE

   BEGIN TRANSACTION TB_S_M_FOREIGN_DEP20_PEO
   BEGIN TRY
    --開啓CURSOR
    OPEN cur_dept_20_peo;
	FETCH NEXT FROM cur_dept_20_peo
	INTO
	     @ws_cd, @score_level_group, @real_a, @real_b, @real_c, @real_d, @real_e, @out_a, @out_b, @out_c, @out_d, @out_e;

	WHILE(@@FETCH_STATUS=0)
		BEGIN

			UPDATE TB_S_M_FOREIGN_DEP20_PEO 
			SET  REAL_A=@real_a, REAL_B=@real_b, REAL_C=@real_c, REAL_D=@real_d, REAL_E=@real_e, REAL_TOTAL=@real_a+@real_b+@real_c+@real_d+@real_e ,
					OUT_REAL_A=@out_a, OUT_REAL_B=@out_b, OUT_REAL_C=@out_c, OUT_REAL_D=@out_d, OUT_REAL_E=@out_e, OUT_REAL_TOTAL=@out_a+@out_b+@out_c+@out_d+@out_e ,
					UPDATED_BY=@USERID ,UPDATED_DT=GETDATE()
			WHERE ASSESS_YEAR=@assess_year and ASSESS_TYPE=@assess_type and DEPT_NO_20=@dept_no and WS_CD=@ws_cd and SCORE_LEVEL_GROUP=@score_level_group;
			print 'assess_year:'+@assess_year+'assess_type:'+@assess_type+'dept_no:'+@dept_no+'ws_cd:'+@ws_cd+'score_level_group:'+@score_level_group;
		FETCH NEXT FROM cur_dept_20_peo
		INTO
	     @ws_cd, @score_level_group, @real_a, @real_b, @real_c, @real_d, @real_e, @out_a, @out_b, @out_c, @out_d, @out_e;
		END;
		CLOSE cur_dept_20_peo;
		DEALLOCATE cur_dept_20_peo;
		COMMIT TRANSACTION TB_S_M_FOREIGN_DEP20_PEO;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION TB_S_M_FOREIGN_DEP20_PEO;
		SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[TB_H_R_SP_LOG:INSERT]'+ERROR_MESSAGE();
		GOTO WriteLog;
	END CATCH

	WriteLog:
	--新增SP記錄檔
	IF @pErr = 0 BEGIN
		SET @proc_status = 'Y';
		SET @proc_log = '處理成功';
	END
	ELSE BEGIN
		IF @proc_status IS NULL SET @proc_status = 'E';
		SET @proc_log = left(@pErrMsg, 600);
	END
	
	BEGIN TRANSACTION ADD_TB_H_R_SP_LOG
		BEGIN TRY
			INSERT INTO TB_H_R_SP_LOG(PROC_ID, PROC_BASE_DT, PROC_DESC, PROC_OTH_DESC, PROC_DT, PROC_STATUS, PROC_LOG, UPDATED_BY, FUNC_ID)
			VALUES(@proc_id, GETDATE(), @proc_desc, NULL, CURRENT_TIMESTAMP, @proc_status, @proc_log, @USERID, @FUNCID);
		
		COMMIT TRANSACTION ADD_TB_H_R_SP_LOG;
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION ADD_TB_H_R_SP_LOG;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[ADD_TB_H_R_SP_LOG:INSERT]:' + ERROR_MESSAGE();
		END CATCH

	RETURN (@pErr)
END;





GO
