USE [FB2DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_S_ASSESS_DIREC_APPROVE]    Script Date: 2026/7/29 下午 04:00:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Max 
-- Create date: 2021/10/26
-- Update date: 2021/10/26
-- Description:	部長考核維護- 考核年度、考核類別,員工ID, 部長部門, 考評, 總評,  使用者id,FunctionID
-- =============================================

CREATE procedure [dbo].[SP_S_FASSESS_DIREC_APPROVE]
	@ASSESS_YEAR varchar(4), 
	@ASSESS_TYPE varchar(1), 
	@DEPT_NO varchar(7),
	@USERID varchar(20),
	@FUNCID varchar(30)
as
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
	SET NOCOUNT ON;
	--錯誤訊息
	DECLARE @pRowCount INT =0;
	DECLARE @pErr INT = 0;
	DECLARE @pErrMsg VARCHAR(1000) = NULL;
	
	DECLARE @proc_id_previous VARCHAR(60) = 'SP_S_FASSESS_DIREC_APPROVE';
	DECLARE @proc_id VARCHAR(60) = 'SP_S_FASSESS_DIREC_APPROVE';
	DECLARE @proc_desc NVARCHAR(120) = '直屬主管簽核送出';
	DECLARE @proc_scheduling VARCHAR(30) = 'CALL';
	DECLARE @proc_log NVARCHAR(600) = NULL;
	DECLARE @proc_status VARCHAR(1) = NULL;
	DECLARE @proc_y_cnt INT;
	DECLARE @ma_a_emp_id VARCHAR(6)='';
	DECLARE @ma_b_emp_id VARCHAR(6)='';
	DECLARE @down_dept_count int =0;
	
	DECLARE @dept_no_20 varchar(7);

	--取得該部門dept_no_20
	SELECT @dept_no_20=DEPT_NO_20 FROM TB_H_R_DEPT_DATA_AD WHERE DEPT_NO=@DEPT_NO;

	--取得協理MA_EMP_ID
	SELECT @ma_a_emp_id=EMP_ID　　From TB_S_M_FOREIGN_DEP20_UP_SIGN WHERE DEPT_NO=@dept_no_20 and DEPT_LEVEL='10';

	--取得二階主管MA_EMP_ID
	SELECT @ma_b_emp_id=EMP_ID　　From TB_S_M_FOREIGN_DEP20_UP_SIGN WHERE DEPT_NO=@dept_no_20 and DEPT_LEVEL='15';

 BEGIN TRANSACTION;
 BEGIN TRY
	--更新TB_S_M_FOREIGN_DIRECTOR_H
	UPDATE TB_S_M_FOREIGN_DIRECTOR_H
    SET    SIGN_YN='Y' ,
         UPDATED_BY = @USERID ,UPDATED_DT = GETDATE() 
         where ASSESS_YEAR = @ASSESS_YEAR and ASSESS_TYPE = @ASSESS_TYPE and DEPT_NO=@DEPT_NO and DIREC_EMP_ID=@USERID;

    --批次新增TB_S_M_FOREIGN_LOG
	 insert into TB_S_M_FOREIGN_LOG (
				 ASSESS_YEAR, ASSESS_TYPE, EMP_ID, GRADE, MEMO, 
				 CREATED_BY,CREATED_DT,FUNC_ID)
     select  A.ASSESS_YEAR, A.ASSESS_TYPE, A.EMP_ID, B.SCORE_FINAL, isnull(COMMENTS,''), 
            @USERID,GETDATE(),@FUNCID 
     FROM   TB_S_M_FOREIGN_DIRECTOR_D A left join 
            TB_S_M_FOREIGN_TARGET B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID left join
            TB_S_M_FOREIGN_DIRECTOR_H D on A.ASSESS_YEAR=D.ASSESS_YEAR and A.ASSESS_TYPE=D.ASSESS_TYPE and A.DEPT_NO = D.DEPT_NO   and A.DIREC_EMP_ID=D.DIREC_EMP_ID
     where A.DEPT_NO=@DEPT_NO and A.ASSESS_YEAR= @ASSESS_YEAR and A.ASSESS_TYPE= @ASSESS_TYPE and A.EMP_ID<>D.DIREC_EMP_ID AND A.DIREC_EMP_ID=@USERID;

	  --批次新增TB_S_M_FOREIGN_ALL_LOG
	 insert into TB_S_M_FOREIGN_ALL_LOG (
				 ASSESS_YEAR, ASSESS_TYPE, EMP_ID, 
				 SEQ_NO, GRADE, MEMO, LEVEL_RATE ,
				 CREATED_BY,CREATED_DT,FUNC_ID)
     select  A.ASSESS_YEAR, A.ASSESS_TYPE, A.EMP_ID, 
			ISNULL((SELECT MAX(SEQ_NO)+1 SEQ_NO FROM TB_S_M_FOREIGN_ALL_LOG WHERE ASSESS_YEAR= A.ASSESS_YEAR and ASSESS_TYPE=A.ASSESS_TYPE and EMP_ID=A.EMP_ID),1)SEQ_NO,
			B.SCORE_FINAL, isnull(COMMENTS,''), A.LEVEL_RATE,
            @USERID,GETDATE(),@FUNCID 
     FROM   TB_S_M_FOREIGN_DIRECTOR_D A left join 
            TB_S_M_FOREIGN_TARGET B on A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE and A.EMP_ID=B.EMP_ID left join
            TB_S_M_FOREIGN_DIRECTOR_H D on A.ASSESS_YEAR=D.ASSESS_YEAR and A.ASSESS_TYPE=D.ASSESS_TYPE and A.DEPT_NO = D.DEPT_NO   and A.DIREC_EMP_ID=D.DIREC_EMP_ID
     where A.DEPT_NO=@DEPT_NO and A.ASSESS_YEAR= @ASSESS_YEAR and A.ASSESS_TYPE= @ASSESS_TYPE and A.EMP_ID<>D.DIREC_EMP_ID AND A.DIREC_EMP_ID=@USERID;
	print @dept_no_20;
	 --更新DEP20_PEO
	 EXEC SP_S_FASSESS_UPD_RO_DEP20_PEO @ASSESS_YEAR=@ASSESS_YEAR, @ASSESS_TYPE=@ASSESS_TYPE, @DEPT_NO=@dept_no_20, @USERID=@USERID, @FUNCID=@FUNCID ;
	
	
	  EXEC SP_S_FASSESS_DEP20_NOTIFY_MAIL @ASSESS_YEAR=@ASSESS_YEAR, @ASSESS_TYPE=@ASSESS_TYPE, @DEPT_NO=@DEPT_NO, @USERID=@USERID, @FUNCID=@FUNCID ;

     --更新TB_S_M_FOREIGN_DEPT_LEVEL	 
		select @down_dept_count=count(*) from TB_S_M_FOREIGN_DEPT_LEVEL A LEFT JOIN
					  TB_S_M_FOREIGN_DEPT_LEVEL B ON A.ASSESS_YEAR=B.ASSESS_YEAR and A.ASSESS_TYPE=B.ASSESS_TYPE  and SUBSTRING(B.LEVEL_RATE,1,len(A.LEVEL_RATE))=A.LEVEL_RATE  
		 where A.DEPT_NO=@DEPT_NO and A.DEPT_NO<>B.DEPT_NO and A.ASSESS_YEAR=@ASSESS_YEAR and A.ASSESS_TYPE=@ASSESS_TYPE AND A.HEAD_EMP_ID=@USERID;
		if @down_dept_count=0
		BEGIN
			UPDATE TB_S_M_FOREIGN_DEPT_LEVEL SET SIGN_YN='Y',  UPDATED_BY = @USERID ,UPDATED_DT = GETDATE()  WHERE ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE and DEPT_NO=@DEPT_NO and HEAD_EMP_ID=@USERID;
		END;
	COMMIT TRANSACTION;

	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION ;
		SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[TB_H_R_SP_LOG:INSERT]'+ERROR_MESSAGE();
		GOTO WriteLog;

	END CATCH

WriteLog:
	--新增SP記錄檔
	IF @pErr = 0 BEGIN
		SET @proc_status = 'Y';
		SET @proc_log = '處理成功';
	END
	ELSE BEGIN
		IF @proc_status IS NULL SET @proc_status = 'E';
		SET @proc_log = left(@pErrMsg, 600);
	END
	
	BEGIN TRANSACTION ADD_TB_H_R_SP_LOG
		BEGIN TRY
			INSERT INTO TB_H_R_SP_LOG(PROC_ID, PROC_BASE_DT, PROC_DESC, PROC_OTH_DESC, PROC_DT, PROC_STATUS, PROC_LOG, UPDATED_BY, FUNC_ID)
			VALUES(@proc_id, @ASSESS_YEAR, @proc_desc, NULL, CURRENT_TIMESTAMP, @proc_status, @proc_log, @USERID, @FUNCID);
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION ADD_TB_H_R_SP_LOG;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[ADD_TB_H_R_SP_LOG:INSERT]:' + ERROR_MESSAGE();
		END CATCH
	COMMIT TRANSACTION ADD_TB_H_R_SP_LOG;

	RETURN (@pErr)	

END





GO


