SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_FASSESS_GEN_SCORE] @ASSESS_YEAR VARCHAR(4),@ASSESS_TYPE VARCHAR(1),@DEPT_NO VARCHAR(6), 
	@USERID varchar(20),
	@FUNCID varchar(30)
AS 
BEGIN
SET NOCOUNT ON;
	--錯誤訊息
	DECLARE @pRowCount INT =0;
	DECLARE @pErr INT = 0;
	DECLARE @pErrMsg VARCHAR(1000) = NULL;
	
	DECLARE @proc_id_previous VARCHAR(60) = 'SP_S_FASSESS_GEN_SCORE';
	DECLARE @proc_id VARCHAR(60) = 'SP_S_FASSESS_GEN_SCORE';
	DECLARE @proc_desc NVARCHAR(120) = '員工評分資料檔生成';
	DECLARE @proc_scheduling VARCHAR(30) = 'CALL';
	DECLARE @proc_log NVARCHAR(600) = NULL;
	DECLARE @proc_status VARCHAR(1) = NULL;
	DECLARE @proc_y_cnt INT;

	BEGIN TRANSACTION
	BEGIN TRY
	--將TB_S_M_ASSESS_ITEM-寫入TB_S_M_ASSESS_ITEM_YEAR
	/**
	DELETE FROM TB_S_M_ASSESS_ITEM_YEAR where ASSESS_YEAR=@ASSESS_YEAR  and ASSESS_TYPE=@ASSESS_TYPE ;

	insert into TB_S_M_ASSESS_ITEM_YEAR(ASSESS_YEAR,ASSESS_TYPE,WS_CD,LEVEL_CD,PJOB_TYPE,ITEM_GROUP,
				CREATED_BY, CREATED_DT,UPDATED_BY, UPDATED_DT,FUNC_ID)
	SELECT @ASSESS_YEAR,ASSESS_TYPE,WS_CD,LEVEL_CD,PJOB_TYPE,ITEM_GROUP,
				@USERID,getDate(),@USERID,getDate(), @FUNCID
	FROM TB_S_M_ASSESS_ITEM where ASSESS_TYPE=@ASSESS_TYPE ;**/
	
	DELETE from TB_S_M_FOREIGN_SCORE where ASSESS_YEAR=@ASSESS_YEAR and ASSESS_TYPE=@ASSESS_TYPE ;
	--生成TB_S_M_FOREIGN_SCORE
	insert into TB_S_M_FOREIGN_SCORE(ASSESS_YEAR, ASSESS_TYPE, EMP_ID,  ITEM_NAME, ITEM_DESC, MAX_GRADE,MNG_GRADE,
								CREATED_BY, CREATED_DT,	UPDATED_BY, UPDATED_DT,FUNC_ID)
	select  distinct X.ASSESS_YEAR,X.ASSESS_TYPE, X.EMP_ID, X.ITEM_NAME, X.ITEM_DESC,convert(int ,X.MAX_GRADE) MAX_GRADE,0,@USERID,getDate(),@USERID,getDate(), @FUNCID
	from
	(
	select A.ASSESS_YEAR,A.ASSESS_TYPE, A.EMP_ID,B.ITEM_NAME,B.ITEM_DESC, B.ASSESS_SCORE as MAX_GRADE
	from								
	(									
		select ASSESS_YEAR,ASSESS_TYPE,EMP_ID								
		 from TB_S_M_FOREIGN_TARGET 								
		where ASSESS_YEAR=@ASSESS_YEAR	 and ASSESS_TYPE=@ASSESS_TYPE								
	)A 									
	inner join									
	(									
		--PJOB_TYPE	職務類型<>''							
		Select ROW_NUMBER() OVER(ORDER BY ITEM_NAME asc) As RowNumber,
				ASSESS_TYPE,ITEM_NAME,ITEM_DESC,ASSESS_SCORE            
		from TB_S_M_FOREIGN_ITEM
		WHERE ASSESS_TYPE=@ASSESS_TYPE

	)B 
	on  A.ASSESS_TYPE = B.ASSESS_TYPE 	
	
	)X	 
	COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION ;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[TB_H_R_SP_LOG:INSERT]'+ERROR_MESSAGE();
			GOTO WriteLog;
	END CATCH  

WriteLog:
	--新增SP記錄檔
	IF @pErr = 0 BEGIN
		SET @proc_status = 'Y';
		SET @proc_log = '處理成功';
	END
	ELSE BEGIN
		IF @proc_status IS NULL SET @proc_status = 'E';
		SET @proc_log = left(@pErrMsg, 600);
	END
	
	BEGIN TRANSACTION ADD_TB_H_R_SP_LOG
		BEGIN TRY
			INSERT INTO TB_H_R_SP_LOG(PROC_ID, PROC_BASE_DT, PROC_DESC, PROC_OTH_DESC, PROC_DT, PROC_STATUS, PROC_LOG, UPDATED_BY, FUNC_ID)
			VALUES(@proc_id, @ASSESS_YEAR, @proc_desc, NULL, CURRENT_TIMESTAMP, @proc_status, @proc_log, @USERID, @FUNCID);
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION ADD_TB_H_R_SP_LOG;
			SELECT @pErr = ERROR_NUMBER(), @pErrMsg = '[ADD_TB_H_R_SP_LOG:INSERT]:' + ERROR_MESSAGE();
		END CATCH
	COMMIT TRANSACTION ADD_TB_H_R_SP_LOG;

	RETURN (@pErr)
END;





GO
